### ISSUE TITLE
Focalplane export not working

### ISSUE THREAD

**Issue by giuspugl** [hpc4cmb/litebirdtask#4]
Hi ,
am not sure this is the right place for this issue. 
when running `lbt_export_focalplane` , i get this error  
```
Traceback (most recent call last):
  File "/global/cscratch1/sd/giuspugl/toast3_software/bin/lbt_export_focalplane", line 8, in <module>
    sys.exit(main())
  File "/global/cscratch1/sd/giuspugl/toast3_software/lib/python3.9/site-packages/litebirdtask/scripts/export_focalplane.py", line 56, in main
    fp.save_hdf5(args.out)
  File "/global/cscratch1/sd/giuspugl/toast3_software/lib/python3.9/site-packages/toast/instrument.py", line 778, in save_hdf5
    table_write_parallel_hdf5(self.detector_data, handle, "focalplane", comm=comm)
  File "/global/cscratch1/sd/giuspugl/toast3_software/lib/python3.9/site-packages/toast/utils.py", line 736, in table_write_parallel_hdf5
    dset = root.create_dataset(name, dset_shape, dtype=dset_type)
AttributeError: 'str' object has no attribute 'create_dataset'
``` 

Think the issue is that  in https://github.com/hpc4cmb/litebirdtask/blob/3a5a5abd9f5144d15e322d01367198cb2da0e3c1/litebirdtask/scripts/export_focalplane.py#L56
`args.out` is a `str` not an hdf5.Group. 

Changing that line into something like : 
```
import h5py 
    f = h5py.File(args.out,'w')
    grp = f.create_group("focalplane")
    fp.save_hdf5(args.out )
    f.close() 
``` 
might do the work. Any suggestion ?

**Comment by keskitalo** [comment]
Please see https://github.com/hpc4cmb/toast/pull/551

**Comment by giuspugl** [comment]
Thanks a lot ! 
I have modified the script accordingly

https://github.com/hpc4cmb/litebirdtask/blob/e28022e2615572de1c1479ebbde17e6cb9eef35f/litebirdtask/scripts/export_focalplane.py#L56
see  PR #5 .
